apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::413519881049:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::413519881049:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EDTZ8J4ZNZV
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T12:32:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1561"
  uid: 477b666b-fab0-43be-ab3d-046fd5083732
